import React from 'react';

import './mainTickerText.scss';

export const MainTickerText = () => {
  return(
    <div className="main-ticker-text-container">
      <div className="scroll text1">
        <div><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span></div>
        <div><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span></div>
      </div>
      <div className="scroll text2">
        <div><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span></div>
        <div><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span><span>FULL-CYCLE EVENT AGENCY FULL-CYCLE EVENT AGENCY</span></div>
      </div>
    </div>
  );
};
